import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
import { pageSocialMetadata } from "@/lib/seo";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing Social Current social media growth orders and website use.", alternates: { canonical: "/terms" }, ...pageSocialMetadata("Terms of Service", "Terms governing Social Current social media growth orders and website use.", "/terms") };

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of service" intro="The rules that apply when you browse Social Current or place an order."><h2>Using the service</h2><p>You must be able to authorize promotion of the profile or content submitted. Do not use Social Current for unlawful, deceptive, abusive, or infringing activity. The target must remain public while delivery is active.</p><h2>Orders and delivery</h2><p>Delivery times are estimates and can vary with platform conditions and provider capacity. Orders may begin quickly and cannot always be changed or cancelled after processing starts. Do not place overlapping orders for the same target while an earlier order is active.</p><h2>Payments</h2><p>Cryptocurrency payments are handled by our payment provider. The checkout page shows the selected asset, network, payment amount, and applicable fees. An order starts only after the payment provider confirms payment. Underpayments, overpayments, expired invoices, or payments sent through the wrong network may require manual review.</p><h2>Platform outcomes</h2><p>Social Current supplies the selected quantity under the package terms. We do not guarantee reach, ranking, verification, revenue, audience retention, or any outcome controlled by a social platform. Customers are responsible for reviewing the rules that apply to their accounts.</p><h2>Availability and liability</h2><p>The service may be interrupted for maintenance, platform changes, or causes outside our control. To the extent permitted by law, liability is limited to the amount paid for the affected order.</p><h2>Changes</h2><p>These terms may change as products, providers, or legal requirements change. Continued use after an update means you accept the revised terms.</p></LegalPage>;
}
