export type Service = {
  slug: string;
  platform: "Instagram" | "TikTok" | "YouTube";
  metric: string;
  title: string;
  shortTitle: string;
  description: string;
  eyebrow: string;
  min: number;
  max: number;
  step: number;
  baseQuantity: number;
  basePrice: number;
  delivery: string;
  retention: string;
  serviceEnv: string;
  color: string;
  highlights: string[];
  faq: { question: string; answer: string }[];
};

export const services: Service[] = [
  {
    slug: "instagram-followers",
    platform: "Instagram",
    metric: "followers",
    title: "Buy Instagram Followers",
    shortTitle: "Instagram followers",
    description: "Build a stronger first impression with gradual, profile-safe follower delivery and no password required.",
    eyebrow: "Most popular",
    min: 100,
    max: 50000,
    step: 100,
    baseQuantity: 1000,
    basePrice: 12.99,
    delivery: "Starts in 5–30 min",
    retention: "30-day refill cover",
    serviceEnv: "SMM_SERVICE_INSTAGRAM_FOLLOWERS",
    color: "coral",
    highlights: ["Gradual delivery", "No password needed", "Refill protection"],
    faq: [
      { question: "How quickly do Instagram followers arrive?", answer: "Most orders begin within 5–30 minutes. Larger packages are paced over a longer window to keep delivery smooth." },
      { question: "Do you need my Instagram password?", answer: "No. We only need the public username or profile link you want the order sent to." },
      { question: "What if the follower count drops?", answer: "Eligible packages include 30-day refill coverage. Contact support with your order number and we will check the order." },
    ],
  },
  {
    slug: "instagram-likes",
    platform: "Instagram",
    metric: "likes",
    title: "Buy Instagram Likes",
    shortTitle: "Instagram likes",
    description: "Add visible momentum to a post or reel with controlled delivery and flexible package sizes.",
    eyebrow: "For posts & reels",
    min: 50,
    max: 25000,
    step: 50,
    baseQuantity: 500,
    basePrice: 6.49,
    delivery: "Starts in 1–15 min",
    retention: "Stable delivery",
    serviceEnv: "SMM_SERVICE_INSTAGRAM_LIKES",
    color: "rose",
    highlights: ["Works with reels", "Fast start", "Private checkout"],
    faq: [
      { question: "Can I buy likes for an Instagram Reel?", answer: "Yes. Paste the public URL of the reel when you place the order." },
      { question: "Can my account be private?", answer: "The post must be public while the order is running so the provider can deliver the engagement." },
      { question: "Will the likes arrive all at once?", answer: "Smaller packages can move quickly. Larger orders use paced delivery to create a steadier pattern." },
    ],
  },
  {
    slug: "instagram-views",
    platform: "Instagram",
    metric: "views",
    title: "Buy Instagram Views",
    shortTitle: "Instagram views",
    description: "Give reels and videos an early visibility signal with quick, trackable view delivery.",
    eyebrow: "Quickest delivery",
    min: 500,
    max: 100000,
    step: 500,
    baseQuantity: 5000,
    basePrice: 10.99,
    delivery: "Starts in 1–10 min",
    retention: "Non-drop views",
    serviceEnv: "SMM_SERVICE_INSTAGRAM_VIEWS",
    color: "gold",
    highlights: ["Reels supported", "Fast delivery", "Live order tracking"],
    faq: [
      { question: "Which Instagram videos are supported?", answer: "Public reels and video posts are supported. Stories and private content are not currently supported." },
      { question: "Is there a maximum order size?", answer: "The storefront supports up to 100,000 views per order. Contact us for larger campaign volumes." },
      { question: "Do views include likes or comments?", answer: "Views are delivered separately. Add likes through the Instagram likes service if you want a more balanced campaign." },
    ],
  },
  {
    slug: "instagram-comments",
    platform: "Instagram",
    metric: "comments",
    title: "Buy Instagram Comments",
    shortTitle: "Instagram comments",
    description: "Add visible conversation to a public post or Reel with selectable comment delivery and no login required.",
    eyebrow: "Conversation boost",
    min: 10,
    max: 5000,
    step: 10,
    baseQuantity: 100,
    basePrice: 9.99,
    delivery: "Starts in 10–45 min",
    retention: "Quality checked",
    serviceEnv: "SMM_SERVICE_INSTAGRAM_COMMENTS",
    color: "mint",
    highlights: ["Public posts & Reels", "No account access", "Trackable delivery"],
    faq: [
      { question: "What type of Instagram comments can I order?", answer: "Available comment styles depend on the connected provider. Review the final service mapping before launch to confirm whether comments are custom, randomized, or emoji-based." },
      { question: "Can comments be delivered to a private post?", answer: "No. The post or Reel must stay public until the order is complete." },
      { question: "Do comments guarantee more engagement?", answer: "No. They add a visible conversation signal, while content quality and real audience interaction determine broader results." },
    ],
  },
  {
    slug: "tiktok-followers",
    platform: "TikTok",
    metric: "followers",
    title: "Buy TikTok Followers",
    shortTitle: "TikTok followers",
    description: "Strengthen your TikTok profile with gradual follower packages built for creators and small brands.",
    eyebrow: "Creator favorite",
    min: 100,
    max: 50000,
    step: 100,
    baseQuantity: 1000,
    basePrice: 24.99,
    delivery: "Starts in 10–45 min",
    retention: "30-day refill cover",
    serviceEnv: "SMM_SERVICE_TIKTOK_FOLLOWERS",
    color: "ink",
    highlights: ["Gradual delivery", "No login required", "Order tracking"],
    faq: [
      { question: "What do you need to deliver TikTok followers?", answer: "Only your public TikTok profile link or username. Never send us your password." },
      { question: "Can I order for a new account?", answer: "Yes, although a complete profile with a few public videos generally creates a more credible first impression." },
      { question: "How long does a large order take?", answer: "Large packages are intentionally paced and can take several days. You can follow progress using your order number." },
    ],
  },
  {
    slug: "tiktok-likes",
    platform: "TikTok",
    metric: "likes",
    title: "Buy TikTok Likes",
    shortTitle: "TikTok likes",
    description: "Support a promising TikTok with fast likes and a simple link-only checkout.",
    eyebrow: "Video boost",
    min: 100,
    max: 50000,
    step: 100,
    baseQuantity: 1000,
    basePrice: 10.99,
    delivery: "Starts in 1–20 min",
    retention: "Stable delivery",
    serviceEnv: "SMM_SERVICE_TIKTOK_LIKES",
    color: "mint",
    highlights: ["Fast start", "Public videos", "No account access"],
    faq: [
      { question: "Can I split likes across several videos?", answer: "Each checkout applies to one video. Place a separate order for each video so progress stays easy to track." },
      { question: "Will you need access to my TikTok?", answer: "No. Paste the public video link and choose a package; no account access is needed." },
      { question: "When should I place an order?", answer: "Many creators place an order shortly after publishing, while the video is already receiving its first organic viewers." },
    ],
  },
  {
    slug: "tiktok-views",
    platform: "TikTok",
    metric: "views",
    title: "Buy TikTok Views",
    shortTitle: "TikTok views",
    description: "Give a public TikTok a stronger starting count with quick, measured view delivery and order tracking.",
    eyebrow: "Fast visibility",
    min: 1000,
    max: 500000,
    step: 1000,
    baseQuantity: 10000,
    basePrice: 8.99,
    delivery: "Starts in 1–15 min",
    retention: "Non-drop option",
    serviceEnv: "SMM_SERVICE_TIKTOK_VIEWS",
    color: "gold",
    highlights: ["Fast start", "Public videos", "Live order status"],
    faq: [
      { question: "How quickly do TikTok views begin?", answer: "Most view orders begin within 1–15 minutes, although timing can vary with package size and provider capacity." },
      { question: "What link should I submit?", answer: "Paste the full public URL of the individual TikTok video you want to promote." },
      { question: "Do views include likes or followers?", answer: "No. Each metric is a separate service so you can choose the mix that fits the campaign." },
    ],
  },
  {
    slug: "tiktok-comments",
    platform: "TikTok",
    metric: "comments",
    title: "Buy TikTok Comments",
    shortTitle: "TikTok comments",
    description: "Build visible activity around a TikTok with comment packages for public videos and clear delivery tracking.",
    eyebrow: "Visible discussion",
    min: 10,
    max: 5000,
    step: 10,
    baseQuantity: 100,
    basePrice: 11.99,
    delivery: "Starts in 10–60 min",
    retention: "Quality checked",
    serviceEnv: "SMM_SERVICE_TIKTOK_COMMENTS",
    color: "rose",
    highlights: ["Video-level delivery", "No login needed", "Simple tracking"],
    faq: [
      { question: "Can I choose the TikTok comment text?", answer: "That depends on the provider service connected at launch. Custom-comment services require a separate comment list during checkout." },
      { question: "Does the video need to be public?", answer: "Yes. Keep the video public throughout delivery so the provider can complete the order." },
      { question: "Should I reply to delivered comments?", answer: "Prioritize genuine audience questions and conversations. Use any paid visibility as support for real community activity." },
    ],
  },
  {
    slug: "youtube-subscribers",
    platform: "YouTube",
    metric: "subscribers",
    title: "Buy YouTube Subscribers",
    shortTitle: "YouTube subscribers",
    description: "Strengthen your channel’s visible audience with gradual subscriber packages and no account access required.",
    eyebrow: "Channel growth",
    min: 100,
    max: 25000,
    step: 100,
    baseQuantity: 1000,
    basePrice: 79.99,
    delivery: "Starts in 1–12 hrs",
    retention: "Refill varies by package",
    serviceEnv: "SMM_SERVICE_YOUTUBE_SUBSCRIBERS",
    color: "coral",
    highlights: ["Gradual delivery", "Public channels", "Package-specific protection"],
    faq: [
      { question: "What channel link should I submit?", answer: "Enter the public YouTube channel handle or its full profile URL." },
      { question: "Will subscribers guarantee monetization?", answer: "No. YouTube applies separate eligibility and policy requirements, and purchased services cannot guarantee monetization or channel approval." },
      { question: "How are larger packages delivered?", answer: "Larger subscriber packages are paced over a longer window. The current provider status is available through order tracking." },
    ],
  },
  {
    slug: "youtube-likes",
    platform: "YouTube",
    metric: "likes",
    title: "Buy YouTube Likes",
    shortTitle: "YouTube likes",
    description: "Add a visible positive signal to a public YouTube video with flexible packages and tracked delivery.",
    eyebrow: "Video engagement",
    min: 50,
    max: 25000,
    step: 50,
    baseQuantity: 500,
    basePrice: 6.99,
    delivery: "Starts in 1–6 hrs",
    retention: "Stable delivery",
    serviceEnv: "SMM_SERVICE_YOUTUBE_LIKES",
    color: "rose",
    highlights: ["Public videos", "Paced delivery", "No channel access"],
    faq: [
      { question: "Can I order likes for a YouTube Short?", answer: "Provider support varies. Confirm that the mapped panel service accepts Shorts before enabling live orders." },
      { question: "Do YouTube likes include views?", answer: "No. Likes and views are separate services and should be selected independently." },
      { question: "When will delivery start?", answer: "Most orders begin within six hours, with larger quantities delivered over a longer period." },
    ],
  },
  {
    slug: "youtube-comments",
    platform: "YouTube",
    metric: "comments",
    title: "Buy YouTube Comments",
    shortTitle: "YouTube comments",
    description: "Add visible discussion to a public YouTube video through trackable comment packages.",
    eyebrow: "Discussion signal",
    min: 10,
    max: 5000,
    step: 10,
    baseQuantity: 100,
    basePrice: 14.99,
    delivery: "Starts in 1–12 hrs",
    retention: "Quality checked",
    serviceEnv: "SMM_SERVICE_YOUTUBE_COMMENTS",
    color: "gold",
    highlights: ["Public videos", "Tracked fulfillment", "No login required"],
    faq: [
      { question: "Are YouTube comments custom written?", answer: "The available format depends on the connected panel service. Custom comments need additional checkout fields before live ordering is enabled." },
      { question: "Can comments be added to any video?", answer: "The video must be public with comments enabled throughout delivery." },
      { question: "Will comments improve video ranking?", answer: "No ranking outcome is guaranteed. Comments are one visible engagement signal among watch behavior, likes, shares, and audience activity." },
    ],
  },
  {
    slug: "youtube-views",
    platform: "YouTube",
    metric: "views",
    title: "Buy YouTube Views",
    shortTitle: "YouTube views",
    description: "Give a public video more visible traction with measured delivery and transparent progress updates.",
    eyebrow: "Long-form reach",
    min: 500,
    max: 100000,
    step: 500,
    baseQuantity: 5000,
    basePrice: 21.99,
    delivery: "Starts in 1–6 hrs",
    retention: "High-retention option",
    serviceEnv: "SMM_SERVICE_YOUTUBE_VIEWS",
    color: "red",
    highlights: ["Paced delivery", "Public videos", "High retention"],
    faq: [
      { question: "How long does YouTube view delivery take?", answer: "Delivery generally begins within six hours and continues gradually. Timing varies with package size and provider capacity." },
      { question: "Can I use an unlisted video?", answer: "Use a public video for reliable delivery. Private videos cannot receive an order." },
      { question: "Does this guarantee subscribers or ranking?", answer: "No. Views can support visible momentum, but results also depend on content quality, audience fit, retention, and consistency." },
    ],
  },
];

export const getService = (slug: string) => services.find((service) => service.slug === slug);

export function calculatePrice(service: Service, quantity: number) {
  const raw = (quantity / service.baseQuantity) * service.basePrice;
  const volumeFactor = quantity >= service.baseQuantity * 10 ? 0.84 : quantity >= service.baseQuantity * 5 ? 0.9 : quantity >= service.baseQuantity * 2 ? 0.95 : 1;
  return Math.max(4.99, raw * volumeFactor);
}
